COMMENT ON COLUMN geoheader.fileid IS 'Always equal to ACS Summary File identification';
COMMENT ON COLUMN geoheader.stusab IS 'State Postal Abbreviation';
COMMENT ON COLUMN geoheader.sumlevel IS 'Summary Level';
COMMENT ON COLUMN geoheader.component IS 'Geographic Component';
COMMENT ON COLUMN geoheader.logrecno IS 'Logical Record Number';
COMMENT ON COLUMN geoheader.us IS 'US';
COMMENT ON COLUMN geoheader.region IS 'Census Region';
COMMENT ON COLUMN geoheader.division IS 'Census Division';
COMMENT ON COLUMN geoheader.statece IS 'State (Census Code)';
COMMENT ON COLUMN geoheader.state IS 'State (FIPS Code)';
COMMENT ON COLUMN geoheader.county IS 'County of current residence';
COMMENT ON COLUMN geoheader.cousub IS 'County Subdivision (FIPS)';
COMMENT ON COLUMN geoheader.place IS 'Place (FIPS Code)';
COMMENT ON COLUMN geoheader.tract IS 'Census Tract';
COMMENT ON COLUMN geoheader.blkgrp IS 'Block Group';
COMMENT ON COLUMN geoheader.concit IS 'Consolidated City';
COMMENT ON COLUMN geoheader.aianhh IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (Census)';
COMMENT ON COLUMN geoheader.aianhhfp IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (FIPS)';
COMMENT ON COLUMN geoheader.aihhtli IS 'American Indian Trust Land/ Hawaiian Home Land Indicator';
COMMENT ON COLUMN geoheader.aitsce IS 'American Indian Tribal Subdivision (Census)';
COMMENT ON COLUMN geoheader.aits IS 'American Indian Tribal Subdivision (FIPS)';
COMMENT ON COLUMN geoheader.anrc IS 'Alaska Native Regional Corporation (FIPS)';
COMMENT ON COLUMN geoheader.cbsa IS 'Metropolitan and Micropolitan Statistical Area';
COMMENT ON COLUMN geoheader.csa IS 'Combined Statistical Area';
COMMENT ON COLUMN geoheader.metdiv IS 'Metropolitan Statistical Area-Metropolitan Division';
COMMENT ON COLUMN geoheader.macc IS 'Metropolitan Area Central City';
COMMENT ON COLUMN geoheader.memi IS 'Metropolitan/Micropolitan Indicator Flag';
COMMENT ON COLUMN geoheader.necta IS 'New England City and Town Area';
COMMENT ON COLUMN geoheader.cnecta IS 'New England City and Town Combined Statistical Area';
COMMENT ON COLUMN geoheader.nectadiv IS 'New England City and Town Area Division';
COMMENT ON COLUMN geoheader.ua IS 'Urban Area';
COMMENT ON COLUMN geoheader.blank1 IS 'Reserved for future use';
COMMENT ON COLUMN geoheader.cdcurr IS 'Current Congressional District ***';
COMMENT ON COLUMN geoheader.sldu IS 'State Legislative District Upper';
COMMENT ON COLUMN geoheader.sldl IS 'State Legislative District Lower';
COMMENT ON COLUMN geoheader.blank2 IS 'Reserved for future use';
COMMENT ON COLUMN geoheader.blank3 IS 'Reserved for future use';
COMMENT ON COLUMN geoheader.zcta5 IS '5-digit ZIP Code Tabulation Area';
COMMENT ON COLUMN geoheader.submcd IS 'Subminor Civil Division (FIPS)';
COMMENT ON COLUMN geoheader.sdelm IS 'State-School District (Elementary)';
COMMENT ON COLUMN geoheader.sdsec IS 'State-School District (Secondary)';
COMMENT ON COLUMN geoheader.sduni IS 'State-School District (Unified)';
COMMENT ON COLUMN geoheader.ur IS 'Urban/Rural';
COMMENT ON COLUMN geoheader.pci IS 'Principal City Indicator';
COMMENT ON COLUMN geoheader.blank5 IS 'Reserved for future use';
COMMENT ON COLUMN geoheader.blank6 IS 'Reserved for future use';
COMMENT ON COLUMN geoheader.puma5 IS 'Public Use Microdata Area - 5% File';
COMMENT ON COLUMN geoheader.blank7 IS 'Reserved for future use';
COMMENT ON COLUMN geoheader.geoid IS 'Geographic Identifier';
COMMENT ON COLUMN geoheader.name IS 'Area Name';
COMMENT ON COLUMN geoheader.bttr IS 'Tribal Tract';
COMMENT ON COLUMN geoheader.btbg IS 'Tribal Block Group';
COMMENT ON COLUMN geoheader.blank8 IS 'Reserved for future use';

